---
# Source: camunda-platform/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: operate-ingress
  labels:
    app.kubernetes.io/app: operate-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  ingressClassName: nginx
  rules:
    - host: gke.upgradingdave.com
      http:
        paths:
          - backend:
              service:
                name: camunda-operate
                port:
                  number: 80
            path: /operate
            pathType: Prefix
  tls:
    - hosts:
        - gke.upgradingdave.com
      secretName: tls-secret