# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml
# See options: https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/README.md

global:
  ingress:
    enabled: true
    className: nginx
    host: "dnslabel.location.cloudapp.azure.com"
#    annotations:
#      cert-manager.io/cluster-issuer: "letsencrypt"
    tls:
      enabled: true
      secretName: "tls-secret"
  image:
      tag: 8.2.0-alpha5
      # tag: latest
      # pullPolicy: Always
  identity:
    auth:
      publicIssuerUrl: "https://dnslabel.location.cloudapp.azure.com/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://dnslabel.location.cloudapp.azure.com/operate"
      tasklist:
        redirectUrl: "https://dnslabel.location.cloudapp.azure.com/tasklist"
      optimize:
        redirectUrl: "https://dnslabel.location.cloudapp.azure.com/optimize"

operate:
  contextPath: "/operate"

tasklist:
  contextPath: "/tasklist"

optimize:
  contextPath: "/optimize"

identity:
  contextPath: "/identity"
  fullURL: "https://dnslabel.location.cloudapp.azure.com/identity"
  
  keycloak:
    extraEnvVars:
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_FRONTEND_URL
        value: "https://dnslabel.location.cloudapp.azure.com/auth"

zeebe-gateway:
  ingress:
    enabled: true
    className: nginx
    host: "dnslabel.location.cloudapp.azure.com"
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"   

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"
  
elasticsearch:
  enabled: true
  imageTag: 7.17.3
  replicas: 1
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  